#!/usr/bin/env bash

function main {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  local nm_resource="$1"; shift

  if [[ "$#" == 0 ]]; then
    set -- .
  fi

  local cache="$shome/.cache"
  cat "$cache/$nm_resource.json" | jq -r -S "$@"
}

source sub "$BASH_SOURCE" "$@"
